### ISSUE TITLE
App crash when trying to stream via Chromecast

### ISSUE THREAD

**Issue by 0xBADEAFFE** [ov3rk1ll/KinoCast#3]
After the last update KinoCast crashes when I try to stream to my Chromecast.

**Comment by wiswedel** [comment]
+1

**Comment by drbeat** [comment]
+1
and mirrors some mirrors dont even load

**Comment by daarky** [comment]
+1 
mirrors work with 1.3.2 but crash with 1.4.0

**Comment by Martina-Neumayer** [comment]
Yeap.. App FC's very much. For example on the source chaneging. Then won't play anything more until the process is killed manually. Strange.. Because this fc has effects on the original kinox.to application. If this fc occurs, then I can not play/cast anything with the original app also.
The phone: LG G3 D855
Rom: Fulmics 4.2

**Comment by daarky** [comment]
Yes. @ov3rk1ll : Could you please fix this? That would be great!

**Comment by drbeat** [comment]
reverting commit f8f8dc35a2459dd577026a9a5c2e11a83d13805c fixes the problems
i can upload a version with the commit reverted but i dont want to be responsible for anything

**Comment by daarky** [comment]
Yes, please. Thank you for your help!

**Comment by daarky** [comment]
@drbeat : Hi! Did you already compile a fixed version?

**Comment by drbeat** [comment]
@daarky 
https://www.dropbox.com/s/487395j9ojmebhy/com.ov3rk1ll.kinocast-debug_v1.4.0.apk?dl=0

**Comment by daarky** [comment]
Thank you!

**Comment by ov3rk1ll** [comment]
Please try with today's 1.5.1 release and open a new issue if there is still a problem
